### ISSUE TITLE
Time format with seconds by default

### ISSUE THREAD

**Issue by ericgl** [Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script#1]
Hi,
Thanks for releasing **7-Zip** with NSIS support.

I was wondering if you could modify one more thing:
By default, **7-Zip** displays the date and time in the **Modified/Created/Accessed** Date columns, with the time section showing only hours and minutes (HH:mm).
I can change it from the **View** menu (see screenshot I linked). However, it only persists in current session. 
Next time I open **7-Zip**, it defaults back to **HH:mm** only. But my preferred time format is **HH:mm:ss** .
Could you modify the code so that the the change is persistent?

Here is a screenshot:
https://imgur.com/a/r77Cg5P

Thanks in advance!
**Eric**

**Comment by Wilenty** [comment]
Hi.
Okay, currently I'm working on some project, but I will try to check it in next week, and I will let you know (here).

**Comment by Wilenty** [comment]
Hello [ericgl](https://github.com/ericgl),
I changed what you asked for and shared as a separate "7zFM_WithSeconds[ByDefault].7z" (for now).

So, now the 7ZIP File Manager displays the date-time with seconds by default.

I'll include this change in the installers in next releases.

Please check it and close this issue. :)

**Comment by ericgl** [comment]
Thanks!!
