### ISSUE TITLE
Additional plugins homepage

### ISSUE THREAD

**Issue by DenisAnisimov** [Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script#4]
I am the author of additional plugins for the 7-Zip that you have integrated into your build. I don't mind using my plugins, but I think it would be more correct to include a link to those plugins homepage https://www.tc4shell.com/en/7zip/ in your documentation.

**Comment by Wilenty** [comment]
Hello,
I thought that you will be satisfied that someone used your plugins in other build of 7-zip. You shared them for free, 7-zip is free and I shared them also for free. But of course I add the link to your homepage as the author of additional plugins used in the plus versions.

Can you look at the reported problem with creating LIZARD archives via 7-zip GUI: https://github.com/Wilenty/7-Zip-X64-X86-with-Extracting-NSIS-script/issues/3 ?

Greetings,
Wilenty

**Comment by DenisAnisimov** [comment]
Ok, thanks.

LIZARD: According to the documentation, the compression level should be in the range 10-49. It must be specified manually in the Parameters field in the form x=10

**Comment by Wilenty** [comment]
Thanks for the explanation,
but 7-zip command-line tool creates the LIZARD archives correctly without additional settings. So, I don't understand why it not work via GUI but works via command-line tool.

![CreatigLIZARDfromCommand-line](https://user-images.githubusercontent.com/61757638/176239462-6c869e44-3a87-4b7b-bc53-127e9ebb3b2b.png)

**Comment by DenisAnisimov** [comment]
The GUI version passes the Level parameter to the plugin (and this causes an error). But the console version does not pass the Level parameter to the plugin.

**Comment by Wilenty** [comment]
Okay, thanks.
